import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "FinPulse AI",
  description: "Prospective Financial Intelligence for Retail Investors",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col font-mono text-sm antialiased">
        <main className="flex-grow flex flex-col relative overflow-hidden">
          {children}
        </main>
        {/* Sticky Legal Footer */}
        <footer className="sticky bottom-0 z-50 w-full bg-surface border-t border-border py-2 px-4 text-center">
          <p className="text-gray-500 text-xs">
            <strong>NOT FINANCIAL ADVICE:</strong> The forecasts and probability bounds generated by FinPulse AI are for informational and educational purposes only. Do not trade real capital based on these predictions.
          </p>
        </footer>
      </body>
    </html>
  );
}
